---
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: image-jenkins-testing-template 
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: "createcred-pipeline" 
  spec:
    source:
      type: "Git"
      git:
        uri: "https://github.com/jcpowermac/ojalloy"
        ref: "master"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
          jenkinsfilePath: jenkins/jobs/credPipelineJob.groovy
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: orgfolder 
  data:
    name: ${JENKINS_ORG_FOLDER_NAME} 
    displayName: ${JENKINS_ORG_FOLDER_NAME}
    repoOwner: ${JENKINS_GITHUB_OWNER}
    pattern: ${JENKINS_GITHUB_REPO}
    credentialsId: ${JENKINS_GITHUB_CRED_ID} 
parameters:
- description: The simple organization folder name
  displayName: Organization folder name 
  name: JENKINS_ORG_FOLDER_NAME
  required: true
- description: Github Owner (https://github.com/owner/repo)  
  displayName: Github Owner 
  name: JENKINS_GITHUB_OWNER
  required: true
- description: Github repository pattern (https://github.com/owner/repo)  
  displayName: Github Repo Pattern
  name: JENKINS_GITHUB_REPO
  required: true
- description: Github username and token secret name
  displayName: GitHub Credentials Name
  name: JENKINS_GITHUB_CRED_ID
  required: true
  value: github

