---
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: image-jenkins-testing-template 
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: "createcred-pipeline" 
  spec:
    source:
      type: "Git"
      git:
        uri: "https://github.com/jcpowermac/ojalloy"
        ref: "master"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
          jenkinsfilePath: jenkins/jobs/credPipelineJob.groovy
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: orgfolder 
  data:
    name: jcpowermac
    displayName: jcpowermac
    repoOwner: jcpowermac
    pattern: ojalloy
    credentialsId: github
