---
apiVersion: v1
kind: BuildConfig
metadata:
  name: "createcred-pipeline" 
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/jcpowermac/ojalloy"
      ref: "testing"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
        jenkinsfilePath: jenkins/jobs/credPipelineJob.groovy 
